### ISSUE TITLE
Hi, vessemer, how to run your project?

### ISSUE THREAD

**Issue by guyucowboy** [vessemer/LungCancerDetection#3]
Hi, vessemer: 
Great work! Thanks for sharing your codes.
How to run your project? What is the step?
Thank you very much!
Best regards.
Gu Yu

**Comment by aszhanghuali** [comment]
Hi,  @vessemer :
Great work! Thanks for sharing your codes.
How to run your project? What is the step?
Thank you very much!
Best regards.

**Comment by vessemer** [comment]
Hi, thanks, I appreciate that you had time to check out this repo,
You can find this approach being integrated in [concept-to-clinic](https://github.com/drivendataorg/concept-to-clinic) project. Precisely it lies in [lr3dcnn](https://github.com/drivendataorg/concept-to-clinic/tree/master/prediction/src/algorithms/classify/src/lr3dcnn) directory. 
There's also a PyTorch implementation of the [Data Science Bowl 2017](http://blog.kaggle.com/2017/06/29/2017-data-science-bowl-predicting-lung-cancer-2nd-place-solution-write-up-daniel-hammack-and-julian-de-wit/) first place [grt123 algorithm](https://github.com/drivendataorg/concept-to-clinic/blob/master/prediction/src/algorithms/classify/src/gtr123_model.py) along with a [nice description](https://github.com/drivendataorg/concept-to-clinic/tree/master/docs/algorithms) for other top 10 algorithms (including grt123 description).
